name: app_review_helper
description: This plugin will make it easier for you to use in-app review with minimal conditions.
version: 0.3.0
homepage: https://github.com/vursin/app_review_helper

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.0
  satisfied_version: ^0.1.0+2
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.7
  in_app_review: ^2.0.6
  update_helper: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
